backend:
  name: git-gateway
  branch: main

# Local backend for development
local_backend: true

media_folder: public/images
public_folder: /images

site_url: https://mdgc.netlify.app
logo_url: https://mdgc.netlify.app/favicon-192x192.png

collections:
  - name: "courses"
    label: "Courses"
    label_singular: "Course"
    folder: "src/content/courses"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Featured Image", name: "featuredImage", widget: "image" }
      - { label: "Address", name: "address", widget: "string", required: false }
      - { label: "Location", name: "location", widget: "map", required: false }
      - { label: "Thumbnail", name: "thumbnail", widget: "image", required: false }
      - { label: "Course Map", name: "courseMap", widget: "image", required: false }
