backend:
  name: git-gateway
  branch: main

media_folder: public/images
public_folder: /images

site_url: https://mdgc.netlify.app
logo_url: https://mdgc.netlify.app/favicon-192x192.png

collections:
  - name: "courses"
    label: "Courses"
    label_singular: "Course"
    folder: "src/content/courses"
    create: true
    editor:
      preview: false
    slug: "{{slug}}"
    extension: "mdx"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Suburb", name: "suburb", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Main Image", name: "mainImage", widget: "image" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image", required: false }
      - { label: "Address", name: "address", widget: "string", required: false }
      - { label: "Location", name: "location", widget: "map", required: false }
      - { label: "Course Map", name: "courseMap", widget: "image", required: false }
